### PR TITLE
fix solana walletConnect esm imports

### PR DESCRIPTION
**Pull request by brunogcpinheiro**
# Changes

- fix: solana wallet connect imports

Screenshot_364

@enesozturk

### CODE REVIEW

**Comment by mdelclaro** [comment]
:pray:

**Comment by brunojlee** [comment]
🙏🏾

**Comment by glitch-txs** [comment]
Thanks! how can I repro this?

**Comment by brunojlee** [comment]
Hi, @glitch-txs ! You can reproduce the issue by adding @web3modal/solana and importing any function/hook from @web3modal/solana/react to a react-app and starting it.

**Review by enesozturk — APPROVED** [review]

**Review by tomiir — APPROVED** [review]

**Comment by enesozturk** [comment]
Good to go ✅

**Pull request merged**
