### PR TITLE
Add Infinity Wallet Connector

### PR DESCRIPTION
**Pull request by InfinityWallet**
We have added support for Infinity Wallet Connector. This allows users to connect with a DApp from within the Infinity Wallet, without needing to use a browser. This feature provides users with a wide range of benefits, such as the ability to have multiple DApps open, or the same DApp open across multiple chains at the same time. When visiting a DApp from an external browser, it will prompt the user via a Deeplink to open that DApp within the Infinity Wallet Browser-less DApps to connect.

**A little about Infinity Wallet:**
Infinity Wallet is the first desktop non-browser extension DeFi & Web3 wallet, supporting over 150,000+ users and securing over $400,000,000 of users funds. We also support the ability to connect via WalletConnect to any DApp or software when outside of Infinity Wallet Browser-less DApps.

### CODE REVIEW

**Comment by InfinityWallet** [comment]
Hello @chadyj, we are following up to see if there is anything else needed? Thanks

**Review by IljaDaderko — APPROVED** [review]

**Comment by chadyj** [comment]
@InfinityWallet @arons1 Sorry for the delay, but happy to approve this.
We have been heads down on v2!

Hope you can check it out too.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Comment by arons1** [comment]
> With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)
> 
> If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

No problem, we have actually already submitted a PR for V2 now also https://github.com/WalletConnect/web3modal/pull/834, hopefully it will be accepted a bit quicker than this one

**Comment by 0xAsimetriq** [comment]
@arons1 awesome, it might be open for a bit, we are actually working on a way to add injected/extension browser management into https://cloud.walletconnect.com similar to mobile and desktop, once that is in I will leave instructions on your pr.

**Pull request closed without merging**
