### PR TITLE
chore: Test Cases table and missing SA tests

### PR DESCRIPTION
**Pull request by lukaisailovic**
# Changes

-  adds basic test cases table

### CODE REVIEW

**Comment by tomiir** [comment]
@lukaisailovic want to merge this and we update it later or will u update with new SIWE + SA test support?

**Comment by enesozturk** [comment]
@lukaisailovic @tomiir I think we could merge this?

**Comment by lukaisailovic** [comment]
@tomiir Can you please update with current testinng state?

**Comment by enesozturk** [comment]
@tomiir @lukaisailovic I think we could close this. IMO it doesn't make sense to keep track of the test cases manually - this will tend to be expired very soon. Engineers shouldn't be responsible of maintaining this list. They should be responsible of adding tests for anything they developed. Since we started doing this. This table doesn't seem useful to me. Wdyt?

**Pull request closed without merging**
