### PR TITLE
feat(ui): remove Apple ProSF font and replace it with google provided Inter

### PR DESCRIPTION
**Pull request by tomiir**
# Breaking Changes

N/A

# Changes

- feat: replace Apple SF Pro font with Inter
- fix:
- chore:

# Associated Issues
closes #[1510](https://github.com/WalletConnect/web3modal/issues/1510)

# Screenshots
Rendered font in gallery
image

### CODE REVIEW

**Review by svenvoskamp — DISMISSED** [review]

**Comment by svenvoskamp** [comment]
You can merge this one if approved by Diane

**Comment by enesozturk** [comment]
@tomiir Are we still waiting for the approval for this? Just checking our PRs which can be merged

**Comment by tomiir** [comment]
This has been approved and I have updatred with base branch. Seem to have los the approves somehow though.

**Review by enesozturk — APPROVED** [review]
LGTM

**Pull request merged**
