### PR TITLE
[FEAT] - Refactor Tally Ho Integration

### PR DESCRIPTION
**Pull request by 0xzoz**
## Motivation

The initial Tally Ho integration was a simple addition of an injected option to the injected configuration slot. This was not ideal for the Tally Ho browser extension for a couple of reasons:

- Tally Ho is not just a wallet, it's a movement towards open source goods. Allowing applications using the web3modal to show Tally even if it is not currently installed is a feature many products had requested.
- The original implementation only showed Tally Ho when it was set as the default wallet within the wallet settings.
- When setting Tally Ho as default it also injected `window.web3` giving web3 precedence and not showing the Tally Ho logo.

### What this PR includes

- If Tally Ho is installed (either using the default setting or not) the injected slot will show Tally Ho and it will take precedence over other installed browser wallets.
- The ability to allow applications using web3modal to have Tally as an option to connect by adding `tallyhowallet` in provider options.
- Have both the injected style and provider option style interact seamlessly depending on the many edge cases.

### CODE REVIEW

**Comment by 0xAskar** [comment]
I would love to have this integrated as soon as possible, as our product on Flips.Finance would benefit from this. We have many users that use Tally and having an independent category on the modal would be great.

**Comment by 0xDaedalus** [comment]
Wondering if there is anything I can do here to help move this PR along?  We are quite keen to get it in - would be a big UX win for users of Tally Ho.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Comment by 0xzoz** [comment]
Thanks @0xAsimetriq we will look into the functionality of V2 and see if there are any changes needed to have Tally Ho work seamlessly

**Pull request closed without merging**
