### PR TITLE
fixed: solflare network mismatch

### PR DESCRIPTION
**Pull request by BeycanDeveloper**
# Breaking Changes

The necessary parameter was sent to the Solflare adapter that needs the network value with a mapping suitable for the network structure in Web3Modal and the network structure in Solana Wallet Adapter packages. Thus, the network mismatch problem was solved.

# Changes

- feat: Solana packages
- fix: Solflare network mismatch
- chore: No

# Associated Issues

closes #...

### CODE REVIEW

**Comment by glitch-txs** [comment]
thanks! how can I reproduce this issue? could you share steps to repro? Thanks!

**Comment by BeycanDeveloper** [comment]
Choose Devnet in Solflare and try sign message.

https://web3modal-laboratory-v3.vercel.app/library/solana/

image

**Comment by BeycanDeveloper** [comment]
@glitch-txs I sent a message to you on Twitter. Can you answer? Also, Web3Modal packages cannot load in Windows. I tried in WSL still have some problems. Why?

**Comment by glitch-txs** [comment]
@BeycanDeveloper you don't need WSL, will check on twitter 👍

**Comment by phoenixVS** [comment]
Thank you, good point! I've reproduced it, but if we rely on default chain it is erroneous for test and dev net
So I propose this approach, also I added listener for chain switching
https://github.com/WalletConnect/web3modal/pull/2304

**Comment by BeycanDeveloper** [comment]
@phoenixVS Yes, you are right, this is a more correct approach :D. I forgot about the situation when the network changed. It must be because my own project is running over the initial network.

**Comment by tomiir** [comment]
@phoenixVS was this fixed by https://github.com/WalletConnect/web3modal/pull/2304 ?
if so, can we close this pr?

**Pull request closed without merging**
